"""人员、账号与权限中心 v3 · 授权真相源（Task 0：只建门禁，不切换运行时）。

本模块把已批准的两份设计资产固化为项目内不可变数据：
1. 99 项权限目录（`PERMISSION_CATALOG` / `ALL_PERMISSIONS`）。
2. 目标路由的边界策略（`ROUTE_POLICIES`）。

设计过程：逐路由取证 + 机械对账双重校核后定稿。

它是授权运行时的唯一真相源。`access_authorization.py` 依据本表做全局
判权；`run_local` 启动时以 `access_v3=True` 接入本表驱动的授权运行时。

边界类型语义：
- PERMISSION：要求一个权限键。
- ALL_OF：列出的权限键必须全部满足。
- SECTIONED：聚合接口按区块独立授权；无权区块不查询、不返回。
- CONDITIONAL：按明确提交动作在多个权限键间条件分流。
- SYSTEM_ADMIN：总钥匙专属，不携带普通权限键。
- SELF_AUTH：本人认证即可。
- AUTHENTICATED_COMMON：登录公共能力。
- AUTHENTICATED_DIRECTORY：轻量人员目录。
- PUBLIC_AUTH：公开登录端点。
- PUBLIC：公开健康/能力端点。
"""
from __future__ import annotations

from collections import namedtuple
from pathlib import Path
from types import MappingProxyType

# 本包目录；测试据此只读 AST 扫描路由声明源，不含任何指向主工作树的绝对路径。
PACKAGE_DIR = Path(__file__).resolve().parent

# 允许的 10 种边界类型。
POLICY_TYPES = frozenset({
    "PUBLIC",
    "PUBLIC_AUTH",
    "SELF_AUTH",
    "AUTHENTICATED_COMMON",
    "AUTHENTICATED_DIRECTORY",
    "PERMISSION",
    "ALL_OF",
    "SECTIONED",
    "CONDITIONAL",
    "SYSTEM_ADMIN",
})

# 99 项权限 UI 唯一真相源；顺序即冻结顺序。
PERMISSION_UI_DEFINITIONS = tuple(
    MappingProxyType(item)
    for item in (
        {'key': 'patient.profile.view', 'module': '患者档案与回收', 'object': '患者资料', 'label': '查看', 'description': '查看患者基本资料、联系方式和就诊摘要。', 'risk': 'sensitive'},
        {'key': 'patient.profile.create', 'module': '患者档案与回收', 'object': '患者资料', 'label': '新建', 'description': '登记一名新患者并保存基本资料。', 'risk': 'sensitive'},
        {'key': 'patient.profile.edit', 'module': '患者档案与回收', 'object': '患者资料', 'label': '编辑', 'description': '修改患者基本资料和联系信息。', 'risk': 'sensitive'},
        {'key': 'patient.profile.merge', 'module': '患者档案与回收', 'object': '患者资料', 'label': '合并', 'description': '把重复患者档案合并为一份，并保留关联记录。', 'risk': 'high'},
        {'key': 'patient.profile.export', 'module': '患者档案与回收', 'object': '患者资料', 'label': '导出', 'description': '批量导出患者资料到文件。', 'risk': 'high'},
        {'key': 'patient.tag.manage', 'module': '患者档案与回收', 'object': '患者标签', 'label': '管理', 'description': '新增、修改或移除患者标签。', 'risk': 'sensitive'},
        {'key': 'patient.group.manage', 'module': '患者档案与回收', 'object': '患者分组', 'label': '管理', 'description': '新增、修改或调整患者分组。', 'risk': 'sensitive'},
        {'key': 'patient.image.view', 'module': '患者档案与回收', 'object': '患者影像', 'label': '查看', 'description': '查看患者的照片、X 光片等影像资料。', 'risk': 'sensitive'},
        {'key': 'patient.image.manage', 'module': '患者档案与回收', 'object': '患者影像', 'label': '上传与编辑', 'description': '上传、修改或整理患者影像资料。', 'risk': 'sensitive'},
        {'key': 'patient.image.delete', 'module': '患者档案与回收', 'object': '患者影像', 'label': '删除', 'description': '删除患者影像资料。', 'risk': 'high'},
        {'key': 'recycle.view', 'module': '患者档案与回收', 'object': '回收站', 'label': '查看', 'description': '查看已删除、可恢复的业务资料。', 'risk': 'sensitive'},
        {'key': 'recycle.restore', 'module': '患者档案与回收', 'object': '回收站', 'label': '恢复', 'description': '把回收站中的资料恢复到业务页面。', 'risk': 'high'},
        {'key': 'appointment.view', 'module': '预约排班', 'object': '预约', 'label': '查看', 'description': '查看患者预约和排班信息。', 'risk': 'sensitive'},
        {'key': 'appointment.create', 'module': '预约排班', 'object': '预约', 'label': '新建', 'description': '为患者创建新的预约。', 'risk': 'normal'},
        {'key': 'appointment.edit', 'module': '预约排班', 'object': '预约', 'label': '编辑', 'description': '修改预约时间、医生或备注。', 'risk': 'normal'},
        {'key': 'appointment.status', 'module': '预约排班', 'object': '预约', 'label': '更新状态', 'description': '更新到诊、完成等预约状态。', 'risk': 'normal'},
        {'key': 'appointment.cancel', 'module': '预约排班', 'object': '预约', 'label': '取消', 'description': '取消患者预约并记录原因。', 'risk': 'sensitive'},
        {'key': 'appointment.delete', 'module': '预约排班', 'object': '预约', 'label': '删除', 'description': '彻底删除预约记录。', 'risk': 'high'},
        {'key': 'medical_record.view', 'module': '临床诊疗', 'object': '电子病历', 'label': '查看', 'description': '查看患者病历正文和诊疗记录。', 'risk': 'sensitive'},
        {'key': 'medical_record.edit', 'module': '临床诊疗', 'object': '电子病历', 'label': '新建与编辑', 'description': '新建或修改患者病历和牙位记录。', 'risk': 'sensitive'},
        {'key': 'medical_record.template.manage', 'module': '临床诊疗', 'object': '病历模板', 'label': '管理', 'description': '新增、修改或删除病历模板。', 'risk': 'sensitive'},
        {'key': 'medical_record.ai.review', 'module': '临床诊疗', 'object': 'AI 病历审核', 'label': '处理', 'description': '查看并确认、认领或废弃 AI 病历草稿。', 'risk': 'sensitive'},
        {'key': 'treatment_order.view', 'module': '临床诊疗', 'object': '治疗项目', 'label': '查看', 'description': '查看患者已开立的治疗项目。', 'risk': 'sensitive'},
        {'key': 'treatment_order.manage', 'module': '临床诊疗', 'object': '治疗项目', 'label': '开立与编辑', 'description': '为患者开立或修改治疗项目。', 'risk': 'sensitive'},
        {'key': 'treatment_order.price', 'module': '临床诊疗', 'object': '治疗项目', 'label': '修改价格', 'description': '修改患者治疗项目的单价或金额。', 'risk': 'high'},
        {'key': 'treatment_order.void', 'module': '临床诊疗', 'object': '治疗项目', 'label': '作废', 'description': '作废已开立的治疗项目或关联账单项目。', 'risk': 'high'},
        {'key': 'treatment_plan.view', 'module': '临床诊疗', 'object': '治疗计划', 'label': '查看', 'description': '查看患者治疗计划和费用内容。', 'risk': 'sensitive'},
        {'key': 'treatment_plan.manage', 'module': '临床诊疗', 'object': '治疗计划', 'label': '新建与编辑', 'description': '新建或修改患者治疗计划。', 'risk': 'sensitive'},
        {'key': 'treatment_plan.status', 'module': '临床诊疗', 'object': '治疗计划', 'label': '更新状态', 'description': '更新治疗计划的确认、执行等状态。', 'risk': 'sensitive'},
        {'key': 'treatment_plan.bill', 'module': '临床诊疗', 'object': '治疗计划', 'label': '生成账单', 'description': '根据治疗计划生成收费账单。', 'risk': 'high'},
        {'key': 'treatment_plan.delete', 'module': '临床诊疗', 'object': '治疗计划', 'label': '删除', 'description': '删除患者治疗计划。', 'risk': 'high'},
        {'key': 'oral_exam.manage', 'module': '临床诊疗', 'object': '口腔检查', 'label': '记录与编辑', 'description': '新增或修改患者口腔检查记录。', 'risk': 'sensitive'},
        {'key': 'surgery.manage', 'module': '临床诊疗', 'object': '手术记录', 'label': '记录与编辑', 'description': '新增或修改患者手术记录。', 'risk': 'sensitive'},
        {'key': 'consent.manage', 'module': '临床诊疗', 'object': '知情同意书', 'label': '签署与管理', 'description': '生成、签署和管理患者知情同意书。', 'risk': 'sensitive'},
        {'key': 'consent.void', 'module': '临床诊疗', 'object': '知情同意书', 'label': '作废', 'description': '作废已经生成或签署的知情同意书。', 'risk': 'high'},
        {'key': 'lab_order.view', 'module': '临床诊疗', 'object': '加工单', 'label': '查看', 'description': '查看义齿等外加工单及其进度。', 'risk': 'sensitive'},
        {'key': 'lab_order.manage', 'module': '临床诊疗', 'object': '加工单', 'label': '新建与编辑', 'description': '新建或修改外加工单和进度。', 'risk': 'sensitive'},
        {'key': 'lab_order.delete', 'module': '临床诊疗', 'object': '加工单', 'label': '删除', 'description': '删除外加工单。', 'risk': 'high'},
        {'key': 'consultation.view', 'module': '咨询、沟通、回访与通话', 'object': '咨询记录', 'label': '查看', 'description': '查看患者咨询内容和跟进情况。', 'risk': 'sensitive'},
        {'key': 'consultation.manage', 'module': '咨询、沟通、回访与通话', 'object': '咨询记录', 'label': '记录与编辑', 'description': '新增或修改患者咨询记录。', 'risk': 'sensitive'},
        {'key': 'communication.view', 'module': '咨询、沟通、回访与通话', 'object': '沟通记录', 'label': '查看', 'description': '查看与患者的沟通内容。', 'risk': 'sensitive'},
        {'key': 'communication.manage', 'module': '咨询、沟通、回访与通话', 'object': '沟通记录', 'label': '记录与编辑', 'description': '新增或修改患者沟通记录。', 'risk': 'sensitive'},
        {'key': 'communication.image.manage', 'module': '咨询、沟通、回访与通话', 'object': '沟通图片', 'label': '上传与删除', 'description': '上传或删除沟通记录中的图片。', 'risk': 'sensitive'},
        {'key': 'communication.delete', 'module': '咨询、沟通、回访与通话', 'object': '沟通记录', 'label': '删除', 'description': '删除患者沟通记录。', 'risk': 'high'},
        {'key': 'return_visit.view', 'module': '咨询、沟通、回访与通话', 'object': '回访记录', 'label': '查看', 'description': '查看患者回访计划和回访内容。', 'risk': 'sensitive'},
        {'key': 'return_visit.manage', 'module': '咨询、沟通、回访与通话', 'object': '回访记录', 'label': '记录与编辑', 'description': '新增或修改患者回访记录。', 'risk': 'sensitive'},
        {'key': 'return_visit.delete', 'module': '咨询、沟通、回访与通话', 'object': '回访记录', 'label': '删除', 'description': '删除患者回访记录。', 'risk': 'high'},
        {'key': 'call_record.view', 'module': '咨询、沟通、回访与通话', 'object': '通话记录', 'label': '查看', 'description': '查看患者通话记录和录音。', 'risk': 'sensitive'},
        {'key': 'call_record.manage', 'module': '咨询、沟通、回访与通话', 'object': '通话记录', 'label': '记录与编辑', 'description': '新增或修改患者通话记录。', 'risk': 'sensitive'},
        {'key': 'call_record.delete', 'module': '咨询、沟通、回访与通话', 'object': '通话记录', 'label': '删除', 'description': '删除患者通话记录。', 'risk': 'high'},
        {'key': 'billing.view', 'module': '收费与会员', 'object': '账单', 'label': '查看', 'description': '查看患者账单、付款和欠费信息。', 'risk': 'sensitive'},
        {'key': 'payment.collect', 'module': '收费与会员', 'object': '收付款', 'label': '收费', 'description': '登记患者付款并更新账单余额。', 'risk': 'high'},
        {'key': 'payment.refund', 'module': '收费与会员', 'object': '收付款', 'label': '退款', 'description': '为患者办理退款并回写账单。', 'risk': 'high'},
        {'key': 'membership.view', 'module': '收费与会员', 'object': '会员账户', 'label': '查看', 'description': '查看患者会员余额和流水。', 'risk': 'sensitive'},
        {'key': 'membership.topup', 'module': '收费与会员', 'object': '会员账户', 'label': '充值', 'description': '为患者会员账户办理充值。', 'risk': 'high'},
        {'key': 'membership.consume', 'module': '收费与会员', 'object': '会员账户', 'label': '扣款', 'description': '从患者会员余额中扣款消费。', 'risk': 'high'},
        {'key': 'membership.refund', 'module': '收费与会员', 'object': '会员账户', 'label': '退款', 'description': '把会员消费退回会员余额。', 'risk': 'high'},
        {'key': 'payment_method.manage', 'module': '收费与会员', 'object': '支付方式', 'label': '管理', 'description': '新增、修改、停用或删除支付方式。', 'risk': 'high'},
        {'key': 'report.finance.view', 'module': '经营报表', 'object': '财务报表', 'label': '查看', 'description': '查看收入、退款和应收等财务汇总。', 'risk': 'sensitive'},
        {'key': 'report.finance.export', 'module': '经营报表', 'object': '财务报表', 'label': '导出', 'description': '导出财务报表明细。', 'risk': 'high'},
        {'key': 'report.arrears.view', 'module': '经营报表', 'object': '欠款报表', 'label': '查看', 'description': '查看患者欠款和应收明细。', 'risk': 'sensitive'},
        {'key': 'report.cashier.view', 'module': '经营报表', 'object': '收银报表', 'label': '查看', 'description': '查看收银员交款和收款汇总。', 'risk': 'sensitive'},
        {'key': 'report.cashier.export', 'module': '经营报表', 'object': '收银报表', 'label': '导出', 'description': '导出收银报表明细。', 'risk': 'high'},
        {'key': 'report.performance.view', 'module': '经营报表', 'object': '绩效报表', 'label': '查看', 'description': '查看员工工作量和绩效数据。', 'risk': 'sensitive'},
        {'key': 'report.operations.view', 'module': '经营报表', 'object': '经营报表', 'label': '查看', 'description': '查看诊所经营和业务趋势。', 'risk': 'sensitive'},
        {'key': 'report.operations.export', 'module': '经营报表', 'object': '经营报表', 'label': '导出', 'description': '导出经营报表明细。', 'risk': 'high'},
        {'key': 'warehouse.inventory.view', 'module': '库房管理', 'object': '库存总览', 'label': '查看', 'description': '查看当前库存数量和库存预警。', 'risk': 'normal'},
        {'key': 'warehouse.item.view', 'module': '库房管理', 'object': '物品档案', 'label': '查看', 'description': '查看库房物品和耗材档案。', 'risk': 'normal'},
        {'key': 'warehouse.item.manage', 'module': '库房管理', 'object': '物品档案', 'label': '管理', 'description': '新增、修改或停用库房物品。', 'risk': 'sensitive'},
        {'key': 'warehouse.supplier.view', 'module': '库房管理', 'object': '供应商', 'label': '查看', 'description': '查看供应商资料。', 'risk': 'normal'},
        {'key': 'warehouse.supplier.manage', 'module': '库房管理', 'object': '供应商', 'label': '管理', 'description': '新增、修改或停用供应商。', 'risk': 'sensitive'},
        {'key': 'warehouse.stock_in.view', 'module': '库房管理', 'object': '入库单', 'label': '查看', 'description': '查看采购入库单和明细。', 'risk': 'normal'},
        {'key': 'warehouse.stock_in.manage', 'module': '库房管理', 'object': '入库单', 'label': '新建与编辑', 'description': '新建或修改未确认的入库单。', 'risk': 'sensitive'},
        {'key': 'warehouse.stock_in.confirm', 'module': '库房管理', 'object': '入库单', 'label': '确认入库', 'description': '确认入库并正式增加库存。', 'risk': 'high'},
        {'key': 'warehouse.stock_out.view', 'module': '库房管理', 'object': '出库单', 'label': '查看', 'description': '查看领用出库单和明细。', 'risk': 'normal'},
        {'key': 'warehouse.stock_out.manage', 'module': '库房管理', 'object': '出库单', 'label': '新建与编辑', 'description': '新建或修改未确认的出库单。', 'risk': 'sensitive'},
        {'key': 'warehouse.stock_out.confirm', 'module': '库房管理', 'object': '出库单', 'label': '确认出库', 'description': '确认出库并正式扣减库存。', 'risk': 'high'},
        {'key': 'warehouse.stocktake.view', 'module': '库房管理', 'object': '盘点单', 'label': '查看', 'description': '查看库存盘点单和差异。', 'risk': 'normal'},
        {'key': 'warehouse.stocktake.manage', 'module': '库房管理', 'object': '盘点单', 'label': '新建与编辑', 'description': '新建或修改未确认的盘点单。', 'risk': 'sensitive'},
        {'key': 'warehouse.stocktake.confirm', 'module': '库房管理', 'object': '盘点单', 'label': '确认盘点', 'description': '确认盘点并按差异调整库存。', 'risk': 'high'},
        {'key': 'instrument.view', 'module': '器械消毒', 'object': '器械档案', 'label': '查看', 'description': '查看器械资料和当前状态。', 'risk': 'normal'},
        {'key': 'instrument.manage', 'module': '器械消毒', 'object': '器械档案', 'label': '管理', 'description': '新增或修改器械资料。', 'risk': 'sensitive'},
        {'key': 'instrument.disable', 'module': '器械消毒', 'object': '器械档案', 'label': '停用', 'description': '停用器械并禁止继续流转。', 'risk': 'sensitive'},
        {'key': 'instrument.delete', 'module': '器械消毒', 'object': '器械档案', 'label': '删除', 'description': '删除器械档案。', 'risk': 'high'},
        {'key': 'sterilization_order.view', 'module': '器械消毒', 'object': '消毒单', 'label': '查看', 'description': '查看器械清洗、消毒和发放记录。', 'risk': 'normal'},
        {'key': 'sterilization_order.manage', 'module': '器械消毒', 'object': '消毒单', 'label': '新建与编辑', 'description': '新建或修改未提交的消毒单。', 'risk': 'sensitive'},
        {'key': 'sterilization_order.submit', 'module': '器械消毒', 'object': '消毒单', 'label': '提交', 'description': '提交消毒单进入审核流程。', 'risk': 'sensitive'},
        {'key': 'sterilization_order.audit', 'module': '器械消毒', 'object': '消毒单', 'label': '审核', 'description': '审核消毒单并确认消毒流转结果。', 'risk': 'high'},
        {'key': 'sterilization_order.cancel_audit', 'module': '器械消毒', 'object': '消毒单', 'label': '取消审核', 'description': '撤销已经完成的消毒单审核。', 'risk': 'high'},
        {'key': 'master_data.view', 'module': '诊所设置、人员、账号与审计', 'object': '基础资料', 'label': '查看', 'description': '查看诊所使用的字典和基础配置。', 'risk': 'normal'},
        {'key': 'master_data.manage', 'module': '诊所设置、人员、账号与审计', 'object': '基础资料', 'label': '管理', 'description': '新增、修改或停用诊疗基础资料。', 'risk': 'sensitive'},
        {'key': 'clinic_settings.manage', 'module': '诊所设置、人员、账号与审计', 'object': '诊所设置', 'label': '修改', 'description': '修改诊所名称、营业和业务设置。', 'risk': 'high'},
        {'key': 'staff.view', 'module': '诊所设置、人员、账号与审计', 'object': '人员档案', 'label': '查看', 'description': '查看员工资料、岗位和在职状态。', 'risk': 'sensitive'},
        {'key': 'staff.edit', 'module': '诊所设置、人员、账号与审计', 'object': '人员档案', 'label': '新建与编辑', 'description': '新增员工或修改员工资料和岗位。', 'risk': 'sensitive'},
        {'key': 'staff.employment', 'module': '诊所设置、人员、账号与审计', 'object': '人员档案', 'label': '离职与复职', 'description': '办理员工离职或复职，并影响其业务可用状态。', 'risk': 'high'},
        {'key': 'account.view', 'module': '诊所设置、人员、账号与审计', 'object': '登录账号', 'label': '查看', 'description': '查看账号用户名、启停和管理员状态。', 'risk': 'sensitive'},
        {'key': 'account.open', 'module': '诊所设置、人员、账号与审计', 'object': '登录账号', 'label': '开通与启停', 'description': '为员工开户，或启用、停用登录账号。', 'risk': 'high'},
        {'key': 'account.security', 'module': '诊所设置、人员、账号与审计', 'object': '登录账号', 'label': '重置密码', 'description': '重置其他账号的登录密码。', 'risk': 'high'},
        {'key': 'audit.view', 'module': '诊所设置、人员、账号与审计', 'object': '操作审计', 'label': '查看', 'description': '查看系统内人员的敏感操作历史。', 'risk': 'high'},
    )
)

PERMISSION_CATALOG = MappingProxyType({
    module: tuple(
        item['key']
        for item in PERMISSION_UI_DEFINITIONS
        if item['module'] == module
    )
    for module in dict.fromkeys(
        item['module'] for item in PERMISSION_UI_DEFINITIONS
    )
})
ALL_PERMISSIONS = frozenset(item['key'] for item in PERMISSION_UI_DEFINITIONS)

# 普通权限之间的显式依赖真相源（Task 2C.1）：键依赖值列出的全部权限键。
# 只按本表判定，不按命名规则（如 xxx.edit 推 xxx.view）猜测；服务侧校验传递闭包。
# 全部键与依赖都必须落在 ALL_PERMISSIONS 内。
PERMISSION_DEPENDENCIES = MappingProxyType({
    'patient.profile.edit': ('patient.profile.view',),
    'patient.profile.merge': ('patient.profile.view',),
    'patient.profile.export': ('patient.profile.view',),
    'patient.tag.manage': ('patient.profile.view',),
    'patient.group.manage': ('patient.profile.view',),
    'patient.image.view': ('patient.profile.view',),
    'patient.image.manage': ('patient.image.view',),
    'patient.image.delete': ('patient.image.view',),
    'recycle.restore': ('recycle.view',),
    'appointment.create': ('appointment.view',),
    'appointment.edit': ('appointment.view',),
    'appointment.status': ('appointment.view',),
    'appointment.cancel': ('appointment.view',),
    'appointment.delete': ('appointment.view',),
    'medical_record.edit': ('medical_record.view',),
    'medical_record.ai.review': ('medical_record.view',),
    'treatment_order.manage': ('treatment_order.view',),
    'treatment_order.price': ('treatment_order.view',),
    'treatment_order.void': ('treatment_order.view',),
    'treatment_plan.manage': ('treatment_plan.view',),
    'treatment_plan.status': ('treatment_plan.view',),
    'treatment_plan.bill': ('treatment_plan.view',),
    'treatment_plan.delete': ('treatment_plan.view',),
    'consent.void': ('consent.manage',),
    'lab_order.manage': ('lab_order.view',),
    'lab_order.delete': ('lab_order.view',),
    'consultation.manage': ('consultation.view',),
    'communication.manage': ('communication.view',),
    'communication.image.manage': ('communication.view',),
    'communication.delete': ('communication.view',),
    'return_visit.manage': ('return_visit.view',),
    'return_visit.delete': ('return_visit.view',),
    'call_record.manage': ('call_record.view',),
    'call_record.delete': ('call_record.view',),
    'payment.collect': ('billing.view',),
    'payment.refund': ('billing.view',),
    'membership.topup': ('membership.view',),
    'membership.consume': ('membership.view',),
    'membership.refund': ('membership.view',),
    'report.finance.export': ('report.finance.view',),
    'report.cashier.export': ('report.cashier.view',),
    'report.operations.export': ('report.operations.view',),
    'warehouse.item.manage': ('warehouse.item.view',),
    'warehouse.supplier.manage': ('warehouse.supplier.view',),
    'warehouse.stock_in.manage': ('warehouse.stock_in.view',),
    'warehouse.stock_in.confirm': ('warehouse.stock_in.view',),
    'warehouse.stock_out.manage': ('warehouse.stock_out.view',),
    'warehouse.stock_out.confirm': ('warehouse.stock_out.view',),
    'warehouse.stocktake.manage': ('warehouse.stocktake.view',),
    'warehouse.stocktake.confirm': ('warehouse.stocktake.view',),
    'instrument.manage': ('instrument.view',),
    'instrument.disable': ('instrument.view',),
    'instrument.delete': ('instrument.view',),
    'sterilization_order.manage': ('sterilization_order.view',),
    'sterilization_order.submit': ('sterilization_order.view',),
    'sterilization_order.audit': ('sterilization_order.view',),
    'sterilization_order.cancel_audit': ('sterilization_order.view',),
    'master_data.manage': ('master_data.view',),
    'staff.edit': ('staff.view',),
    'staff.employment': ('staff.view',),
    'account.open': ('account.view',),
    'account.security': ('account.view',),
})

# 系统管理员专属能力（总钥匙语义，不属于 99 项普通权限，不可分配给角色）。
# 值是给日后 GUI 展示的中文说明；键只作稳定标识，不进 role_permissions。
SYSTEM_ADMIN_CAPABILITIES = MappingProxyType({
    'system_admin.role_permissions.manage': '修改角色权限',
    'system_admin.grant': '授予/撤销系统管理员',
    'system_admin.backup.download': '下载数据库备份',
    'system_admin.sync.run': '执行全量同步',
    'system_admin.migration.run': '执行数据迁移',
})

# 旧 role.manage 与上述专属能力一样，配置角色权限时整单拒绝，不静默过滤。
NON_ASSIGNABLE_PERMISSIONS = frozenset(SYSTEM_ADMIN_CAPABILITIES) | {'role.manage'}

RoutePolicy = namedtuple(
    "RoutePolicy",
    "method path source function policy_type permissions note",
)

# 目标路由的显式策略（已批准设计数据，按 (path, method) 稳定排序）。
# 每行：(method, path, source, function, policy_type, permissions, note)
_ROUTE_POLICY_ROWS = (
    ('GET', '/api/ai-drafts', 'routes/ai_drafts.py', 'list_ai_drafts', 'ALL_OF', ('medical_record.view', 'medical_record.ai.review', ), '草稿含病历正文，队列权限不能替代病历查看权限'),
    ('POST', '/api/ai-drafts/{record_id}/confirm', 'routes/ai_drafts.py', 'confirm_ai_draft', 'ALL_OF', ('medical_record.edit', 'medical_record.ai.review', ), '确认/废弃/认领会写病历，必须同时具备编辑权限'),
    ('POST', '/api/ai-drafts/{record_id}/discard', 'routes/ai_drafts.py', 'discard_ai_draft', 'ALL_OF', ('medical_record.edit', 'medical_record.ai.review', ), '确认/废弃/认领会写病历，必须同时具备编辑权限'),
    ('POST', '/api/ai-unclaimed/{unclaimed_id}/claim', 'routes/ai_drafts.py', 'claim_ai_unclaimed', 'ALL_OF', ('medical_record.edit', 'medical_record.ai.review', ), '确认/废弃/认领会写病历，必须同时具备编辑权限'),
    ('POST', '/api/ai-unclaimed/{unclaimed_id}/discard', 'routes/ai_drafts.py', 'discard_ai_unclaimed', 'ALL_OF', ('medical_record.edit', 'medical_record.ai.review', ), '确认/废弃/认领会写病历，必须同时具备编辑权限'),
    ('GET', '/api/appointments', 'routes/appointments.py', 'appointment_list', 'PERMISSION', ('appointment.view', ), None),
    ('POST', '/api/appointments', 'routes/appointments.py', 'create_appointment', 'PERMISSION', ('appointment.create', ), None),
    ('GET', '/api/appointments/summary', 'routes/appointments.py', 'appointment_summary', 'PERMISSION', ('appointment.view', ), None),
    ('DELETE', '/api/appointments/{appointment_id}', 'routes/appointments.py', 'delete_appointment', 'PERMISSION', ('appointment.delete', ), None),
    ('GET', '/api/appointments/{appointment_id}', 'routes/appointments.py', 'get_appointment', 'PERMISSION', ('appointment.view', ), None),
    ('PUT', '/api/appointments/{appointment_id}', 'routes/appointments.py', 'update_appointment', 'CONDITIONAL', ('appointment.edit', 'appointment.status', 'appointment.cancel', ), '按提交字段/专用端点'),
    ('GET', '/api/audit-logs', 'routes/audit_logs.py', 'audit_logs', 'PERMISSION', ('audit.view', ), None),
    ('GET', '/api/audit-logs/operators', 'routes/audit_logs.py', 'audit_operators', 'PERMISSION', ('audit.view', ), None),
    ('POST', '/api/auth/change-password', 'routes/users.py', 'change_password', 'SELF_AUTH', (), None),
    ('POST', '/api/auth/login', 'access_auth.py', 'access_login', 'PUBLIC_AUTH', (), None),
    ('POST', '/api/auth/logout', 'access_auth.py', 'access_logout', 'SELF_AUTH', (), None),
    ('GET', '/api/auth/me', 'access_auth.py', 'access_me', 'SELF_AUTH', (), None),
    ('POST', '/api/auth/reauth', 'access_auth.py', 'access_reauth', 'SELF_AUTH', (), None),
    ('POST', '/api/backup', 'routes/backup.py', 'create_backup', 'SYSTEM_ADMIN', (), None),
    ('GET', '/api/backup/list', 'routes/backup.py', 'list_backups', 'SYSTEM_ADMIN', (), None),
    ('GET', '/api/backup/{name}/download', 'routes/backup.py', 'download_backup', 'SYSTEM_ADMIN', (), None),
    ('GET', '/api/bills', 'routes/bills.py', 'bill_list', 'PERMISSION', ('billing.view', ), None),
    ('GET', '/api/bills/{bill_id}', 'routes/billing_ops.py', 'get_bill', 'PERMISSION', ('billing.view', ), None),
    ('POST', '/api/bills/{bill_id}/pay', 'routes/billing_ops.py', 'confirm_payment', 'PERMISSION', ('payment.collect', ), None),
    ('POST', '/api/bills/{bill_id}/refund', 'routes/billing_ops.py', 'refund_bill', 'PERMISSION', ('payment.refund', ), None),
    ('POST', '/api/bills/{bill_id}/void-order', 'routes/treatment_orders.py', 'void_order_by_bill', 'PERMISSION', ('treatment_order.void', ), None),
    ('DELETE', '/api/calls/{call_id}', 'routes/calls.py', 'delete_call', 'PERMISSION', ('call_record.delete', ), None),
    ('PATCH', '/api/calls/{call_id}', 'routes/calls.py', 'update_call', 'PERMISSION', ('call_record.manage', ), None),
    ('GET', '/api/calls/{call_id}/recording', 'routes/calls.py', 'call_recording', 'PERMISSION', ('call_record.view', ), None),
    ('GET', '/api/capabilities', 'api.py', 'capabilities', 'PUBLIC', (), None),
    ('GET', '/api/communications', 'routes/communications.py', 'list_communications_ledger', 'ALL_OF', ('patient.profile.view', 'communication.view', ), '跨患者沟通台账同时需要患者档案与沟通查看权限'),
    ('DELETE', '/api/communications/{communication_id}', 'routes/communications.py', 'delete_communication', 'PERMISSION', ('communication.delete', ), None),
    ('PATCH', '/api/communications/{communication_id}', 'routes/communications.py', 'update_communication', 'PERMISSION', ('communication.manage', ), None),
    ('POST', '/api/communications/{communication_id}/images', 'routes/communications.py', 'upload_communication_image', 'PERMISSION', ('communication.image.manage', ), None),
    ('DELETE', '/api/communications/{communication_id}/images/{image_id}', 'routes/communications.py', 'delete_communication_image', 'PERMISSION', ('communication.image.manage', ), None),
    ('GET', '/api/communications/{communication_id}/images/{image_id}/file', 'routes/communications.py', 'communication_image_file', 'PERMISSION', ('communication.view', ), None),
    ('GET', '/api/consent-documents/{document_id}', 'routes/consent_forms.py', 'get_document', 'PERMISSION', ('consent.manage', ), None),
    ('POST', '/api/consent-documents/{document_id}/void', 'routes/consent_forms.py', 'void_document', 'PERMISSION', ('consent.void', ), None),
    ('GET', '/api/consent-templates', 'routes/consent_forms.py', 'list_templates', 'PERMISSION', ('consent.manage', ), None),
    ('POST', '/api/consent-templates', 'routes/consent_forms.py', 'create_template', 'PERMISSION', ('consent.manage', ), None),
    ('GET', '/api/consent-templates/{template_id}', 'routes/consent_forms.py', 'get_template', 'PERMISSION', ('consent.manage', ), None),
    ('GET', '/api/customer-hub/today', 'routes/customer_hub.py', 'customer_hub_today', 'SECTIONED', ('patient.profile.view', 'communication.view', 'call_record.view', 'return_visit.view', ), '患者查看是入口门禁；沟通、通话、回访区块按各自权限返回或隐藏'),
    ('GET', '/api/dictionaries', 'routes/master_data.py', 'dictionaries', 'PERMISSION', ('master_data.view', ), None),
    ('POST', '/api/dictionaries', 'routes/master_data.py', 'create_dictionary', 'PERMISSION', ('master_data.manage', ), '仅回访计划类型开放在线维护'),
    ('POST', '/api/dictionaries/{dict_id}/stop', 'routes/master_data.py', 'stop_dictionary', 'PERMISSION', ('master_data.manage', ), '仅回访计划类型开放在线维护'),
    ('GET', '/api/dispatch', 'routes/sterilize_dispatch.py', 'list_dispatch', 'PERMISSION', ('sterilization_order.view', ), None),
    ('POST', '/api/dispatch', 'routes/sterilize_dispatch.py', 'create_dispatch', 'PERMISSION', ('sterilization_order.manage', ), None),
    ('DELETE', '/api/dispatch/{dispatch_id}', 'routes/sterilize_dispatch.py', 'delete_dispatch', 'PERMISSION', ('sterilization_order.manage', ), None),
    ('GET', '/api/dispatch/{dispatch_id}', 'routes/sterilize_dispatch.py', 'get_dispatch', 'PERMISSION', ('sterilization_order.view', ), None),
    ('PUT', '/api/dispatch/{dispatch_id}', 'routes/sterilize_dispatch.py', 'update_dispatch', 'PERMISSION', ('sterilization_order.manage', ), None),
    ('POST', '/api/dispatch/{dispatch_id}/audit', 'routes/sterilize_dispatch.py', 'audit_dispatch', 'PERMISSION', ('sterilization_order.audit', ), None),
    ('POST', '/api/dispatch/{dispatch_id}/cancel-audit', 'routes/sterilize_dispatch.py', 'cancel_audit_dispatch', 'PERMISSION', ('sterilization_order.cancel_audit', ), None),
    ('POST', '/api/dispatch/{dispatch_id}/submit', 'routes/sterilize_dispatch.py', 'submit_dispatch', 'PERMISSION', ('sterilization_order.submit', ), None),
    ('GET', '/api/handle-items', 'routes/master_data.py', 'handle_items', 'PERMISSION', ('master_data.view', ), None),
    ('POST', '/api/handle-items', 'routes/master_data.py', 'create_handle_item', 'PERMISSION', ('master_data.manage', ), None),
    ('GET', '/api/handle-items/manage', 'routes/master_data.py', 'manage_handle_items', 'PERMISSION', ('master_data.manage', ), None),
    ('DELETE', '/api/handle-items/{handle_id}', 'routes/master_data.py', 'delete_handle_item', 'PERMISSION', ('master_data.manage', ), None),
    ('PUT', '/api/handle-items/{handle_id}', 'routes/master_data.py', 'update_handle_item', 'PERMISSION', ('master_data.manage', ), None),
    ('POST', '/api/handle-items/{handle_id}/restore', 'routes/master_data.py', 'restore_handle_item', 'PERMISSION', ('master_data.manage', ), None),
    ('GET', '/api/health', 'api.py', 'health', 'PUBLIC', (), None),
    ('GET', '/api/instrument-categories', 'routes/sterilization.py', 'list_categories', 'PERMISSION', ('instrument.view', ), None),
    ('POST', '/api/instrument-categories', 'routes/sterilization.py', 'create_category', 'PERMISSION', ('instrument.manage', ), None),
    ('DELETE', '/api/instrument-categories/{category_id}', 'routes/sterilization.py', 'delete_category', 'PERMISSION', ('instrument.manage', ), None),
    ('PUT', '/api/instrument-categories/{category_id}', 'routes/sterilization.py', 'update_category', 'PERMISSION', ('instrument.manage', ), None),
    ('GET', '/api/instruments', 'routes/sterilization.py', 'list_instruments', 'PERMISSION', ('instrument.view', ), None),
    ('POST', '/api/instruments', 'routes/sterilization.py', 'create_instrument', 'PERMISSION', ('instrument.manage', ), None),
    ('DELETE', '/api/instruments/{instrument_id}', 'routes/sterilization.py', 'delete_instrument', 'PERMISSION', ('instrument.delete', ), None),
    ('PUT', '/api/instruments/{instrument_id}', 'routes/sterilization.py', 'update_instrument', 'PERMISSION', ('instrument.manage', ), None),
    ('PUT', '/api/instruments/{instrument_id}/disable', 'routes/sterilization.py', 'disable_instrument', 'PERMISSION', ('instrument.disable', ), None),
    ('GET', '/api/lab-config/{kind}', 'routes/lab_orders.py', 'get_config', 'PERMISSION', ('lab_order.view', ), None),
    ('PUT', '/api/lab-config/{kind}', 'routes/lab_orders.py', 'put_config', 'PERMISSION', ('lab_order.manage', ), None),
    ('DELETE', '/api/lab-orders/images/{img_id}', 'routes/lab_orders.py', 'delete_image', 'PERMISSION', ('lab_order.delete', ), None),
    ('GET', '/api/lab-orders/images/{img_id}/file', 'routes/lab_orders.py', 'image_file', 'PERMISSION', ('lab_order.view', ), None),
    ('GET', '/api/lab-orders/in-progress', 'routes/lab_orders.py', 'in_progress_ledger', 'PERMISSION', ('lab_order.view', ), None),
    ('POST', '/api/lab-orders/{order_id}/images', 'routes/lab_orders.py', 'upload_image', 'PERMISSION', ('lab_order.manage', ), None),
    ('PUT', '/api/lab-orders/{order_id}/return', 'routes/lab_orders.py', 'mark_returned', 'PERMISSION', ('lab_order.manage', ), None),
    ('POST', '/api/medical-records', 'routes/medical_records.py', 'create_medical_record', 'PERMISSION', ('medical_record.edit', ), None),
    ('PUT', '/api/medical-records/{record_id}', 'routes/medical_records.py', 'update_medical_record', 'PERMISSION', ('medical_record.edit', ), None),
    ('GET', '/api/medical-records/{record_id}/items', 'routes/record_items.py', 'list_record_items', 'PERMISSION', ('medical_record.view', ), None),
    ('PUT', '/api/medical-records/{record_id}/items', 'routes/record_items.py', 'replace_record_items', 'PERMISSION', ('medical_record.edit', ), None),
    ('GET', '/api/medical-templates', 'routes/templates.py', 'medical_templates', 'PERMISSION', ('medical_record.view', ), None),
    ('POST', '/api/medical-templates', 'routes/templates.py', 'save_as_template', 'PERMISSION', ('medical_record.template.manage', ), None),
    ('GET', '/api/my-settings/{key}', 'routes/user_settings.py', 'get_setting', 'SELF_AUTH', (), None),
    ('PUT', '/api/my-settings/{key}', 'routes/user_settings.py', 'put_setting', 'SELF_AUTH', (), None),
    ('POST', '/api/ocr/patient-card', 'routes/ocr.py', 'recognize_patient_card', 'PERMISSION', ('patient.profile.create', ), None),
    ('GET', '/api/ocr/status', 'routes/ocr.py', 'ocr_status', 'PERMISSION', ('patient.profile.create', ), None),
    ('GET', '/api/patient-groups', 'routes/patient_groups.py', 'patient_groups', 'PERMISSION', ('patient.group.manage', ), None),
    ('DELETE', '/api/patient-tags/{tag_id}', 'routes/patient_tags.py', 'delete_tag', 'PERMISSION', ('patient.tag.manage', ), None),
    ('GET', '/api/patients', 'routes/patients.py', 'patients', 'SECTIONED', ('patient.profile.view', 'billing.view', ), '患者查看是入口门禁；金额字段按 billing.view 与财务数据范围掩码'),
    ('POST', '/api/patients', 'routes/patient_create.py', 'create_patient', 'PERMISSION', ('patient.profile.create', ), None),
    ('GET', '/api/patients/export', 'routes/patients.py', 'patients_export', 'PERMISSION', ('patient.profile.export', ), None),
    ('POST', '/api/patients/import', 'routes/patient_create.py', 'import_patients', 'SYSTEM_ADMIN', (), '批量数据进出与数据备份同口径:仅系统管理员'),
    ('GET', '/api/patients/{patient_identity}', 'routes/patients.py', 'patient_detail', 'SECTIONED', ('patient.profile.view', 'billing.view', ), '患者查看是入口门禁；金额字段按 billing.view 与财务数据范围掩码'),
    ('PUT', '/api/patients/{patient_identity}', 'routes/patients.py', 'update_patient', 'PERMISSION', ('patient.profile.edit', ), None),
    ('GET', '/api/patients/{patient_identity}/audit-logs', 'routes/audit_logs.py', 'patient_audit_logs', 'PERMISSION', ('patient.profile.view', ), None),
    ('GET', '/api/patients/{patient_identity}/avatar', 'routes/patient_assets.py', 'get_avatar', 'PERMISSION', ('patient.image.view', ), None),
    ('POST', '/api/patients/{patient_identity}/avatar', 'routes/patient_assets.py', 'upload_avatar', 'PERMISSION', ('patient.image.manage', ), None),
    ('GET', '/api/patients/{patient_identity}/calls', 'routes/calls.py', 'list_patient_calls', 'PERMISSION', ('call_record.view', ), None),
    ('POST', '/api/patients/{patient_identity}/calls', 'routes/calls.py', 'upload_patient_call', 'PERMISSION', ('call_record.manage', ), None),
    ('POST', '/api/patients/{patient_identity}/check-in', 'routes/appointments.py', 'check_in_patient', 'ALL_OF', ('appointment.create', 'appointment.status', 'appointment.edit', ), '到店挂号同时涵盖新建、状态推进和预约字段修改'),
    ('GET', '/api/patients/{patient_identity}/communications', 'routes/communications.py', 'list_patient_communications', 'PERMISSION', ('communication.view', ), None),
    ('POST', '/api/patients/{patient_identity}/communications', 'routes/communications.py', 'create_communication', 'PERMISSION', ('communication.manage', ), None),
    ('GET', '/api/patients/{patient_identity}/consent-documents', 'routes/consent_forms.py', 'list_documents', 'PERMISSION', ('consent.manage', ), None),
    ('POST', '/api/patients/{patient_identity}/consent-documents', 'routes/consent_forms.py', 'create_document', 'PERMISSION', ('consent.manage', ), None),
    ('GET', '/api/patients/{patient_identity}/consults', 'routes/consults.py', 'list_consults', 'PERMISSION', ('consultation.view', ), None),
    ('POST', '/api/patients/{patient_identity}/consults', 'routes/consults.py', 'create_consult', 'PERMISSION', ('consultation.manage', ), None),
    ('POST', '/api/patients/{patient_identity}/image-sets', 'routes/patient_assets.py', 'mark_image_set', 'PERMISSION', ('patient.image.manage', ), None),
    ('DELETE', '/api/patients/{patient_identity}/image-sets/{image_date}', 'routes/patient_assets.py', 'unmark_image_set', 'PERMISSION', ('patient.image.delete', ), None),
    ('GET', '/api/patients/{patient_identity}/images', 'routes/patient_assets.py', 'patient_image_list', 'PERMISSION', ('patient.image.view', ), None),
    ('POST', '/api/patients/{patient_identity}/images', 'routes/patient_assets.py', 'upload_patient_image', 'PERMISSION', ('patient.image.manage', ), None),
    ('DELETE', '/api/patients/{patient_identity}/images/{image_id}', 'routes/patient_assets.py', 'delete_patient_image', 'PERMISSION', ('patient.image.delete', ), None),
    ('GET', '/api/patients/{patient_identity}/images/{image_id}/file', 'routes/patient_assets.py', 'patient_image_file', 'PERMISSION', ('patient.image.view', ), None),
    ('POST', '/api/patients/{patient_identity}/images/{image_id}/orient', 'routes/patient_assets.py', 'orient_patient_image', 'PERMISSION', ('patient.image.manage', ), None),
    ('GET', '/api/patients/{patient_identity}/lab-orders', 'routes/lab_orders.py', 'list_orders', 'PERMISSION', ('lab_order.view', ), None),
    ('POST', '/api/patients/{patient_identity}/lab-orders', 'routes/lab_orders.py', 'create_order', 'PERMISSION', ('lab_order.manage', ), None),
    ('DELETE', '/api/patients/{patient_identity}/lab-orders/{order_id}', 'routes/lab_orders.py', 'delete_order', 'PERMISSION', ('lab_order.delete', ), None),
    ('PUT', '/api/patients/{patient_identity}/lab-orders/{order_id}', 'routes/lab_orders.py', 'update_order', 'PERMISSION', ('lab_order.manage', ), None),
    ('GET', '/api/patients/{patient_identity}/member-account', 'routes/membership.py', 'get_member_account', 'PERMISSION', ('membership.view', ), None),
    ('POST', '/api/patients/{patient_identity}/member-account/consume', 'routes/membership.py', 'consume', 'PERMISSION', ('membership.consume', ), None),
    ('POST', '/api/patients/{patient_identity}/member-account/refund', 'routes/membership.py', 'refund', 'PERMISSION', ('membership.refund', ), None),
    ('POST', '/api/patients/{patient_identity}/member-account/topup', 'routes/membership.py', 'topup', 'PERMISSION', ('membership.topup', ), None),
    ('POST', '/api/patients/{patient_identity}/notes', 'routes/patients.py', 'create_note', 'PERMISSION', ('patient.profile.edit', ), None),
    ('GET', '/api/patients/{patient_identity}/oral-exams', 'routes/oral_exams.py', 'list_oral_exams', 'PERMISSION', ('oral_exam.manage', ), None),
    ('POST', '/api/patients/{patient_identity}/oral-exams', 'routes/oral_exams.py', 'create_oral_exam', 'PERMISSION', ('oral_exam.manage', ), None),
    ('GET', '/api/patients/{patient_identity}/record-items', 'routes/record_items.py', 'patient_record_items', 'PERMISSION', ('medical_record.view', ), None),
    ('POST', '/api/patients/{patient_identity}/return-visits', 'routes/return_visit_ops.py', 'create_return_visit', 'PERMISSION', ('return_visit.manage', ), None),
    ('GET', '/api/patients/{patient_identity}/summary', 'routes/patient_assets.py', 'patient_summary', 'SECTIONED', ('patient.profile.view', 'billing.view', ), '患者查看是入口门禁；金额字段按 billing.view 与财务数据范围掩码'),
    ('GET', '/api/patients/{patient_identity}/surgeries', 'routes/surgeries.py', 'list_surgeries', 'PERMISSION', ('surgery.manage', ), None),
    ('POST', '/api/patients/{patient_identity}/surgeries', 'routes/surgeries.py', 'create_surgery', 'PERMISSION', ('surgery.manage', ), None),
    ('GET', '/api/patients/{patient_identity}/teeth/summary', 'routes/record_items.py', 'teeth_summary', 'PERMISSION', ('medical_record.view', ), None),
    ('GET', '/api/patients/{patient_identity}/teeth/{tooth}/history', 'routes/record_items.py', 'tooth_history', 'PERMISSION', ('medical_record.view', ), None),
    ('GET', '/api/patients/{patient_identity}/today-visit', 'routes/treatment_orders.py', 'today_visit', 'PERMISSION', ('treatment_order.view', ), None),
    ('GET', '/api/patients/{patient_identity}/treatment-orders', 'routes/treatment_orders.py', 'list_orders', 'PERMISSION', ('treatment_order.view', ), None),
    ('POST', '/api/patients/{patient_identity}/treatment-orders', 'routes/treatment_orders.py', 'create_order', 'PERMISSION', ('treatment_order.manage', ), None),
    ('POST', '/api/patients/{patient_identity}/treatment-orders/ensure-arrival', 'routes/treatment_orders.py', 'ensure_arrival_order', 'PERMISSION', ('treatment_order.manage', ), None),
    ('GET', '/api/patients/{patient_identity}/treatment-plans', 'routes/treatment_plans.py', 'list_treatment_plans', 'PERMISSION', ('treatment_plan.view', ), None),
    ('POST', '/api/patients/{patient_identity}/treatment-plans', 'routes/treatment_plans.py', 'create_treatment_plan', 'PERMISSION', ('treatment_plan.manage', ), None),
    ('GET', '/api/patients/{patient_identity}/treatments', 'routes/patient_assets.py', 'patient_treatments', 'SECTIONED', ('patient.profile.view', 'billing.view', ), '患者查看是入口门禁；金额字段按 billing.view 与财务数据范围掩码'),
    ('GET', '/api/patients/{patient_identity}/visits', 'routes/patient_assets.py', 'patient_visits', 'SECTIONED', ('patient.profile.view', 'billing.view', ), '患者查看是入口门禁；金额字段按 billing.view 与财务数据范围掩码'),
    ('GET', '/api/patients/{pid}/tags', 'routes/patient_tags.py', 'list_tags', 'PERMISSION', ('patient.profile.view', ), None),
    ('POST', '/api/patients/{pid}/tags', 'routes/patient_tags.py', 'add_tag', 'PERMISSION', ('patient.tag.manage', ), None),
    ('POST', '/api/patients/{primary}/merge', 'routes/patient_merge.py', 'merge_patient', 'PERMISSION', ('patient.profile.merge', ), None),
    ('GET', '/api/recycle-bin', 'routes/recycle_bin.py', 'list_recycle', 'PERMISSION', ('recycle.view', ), None),
    ('POST', '/api/recycle-bin/restore', 'routes/recycle_bin.py', 'restore', 'PERMISSION', ('recycle.restore', ), None),
    ('GET', '/api/referral-sources', 'routes/referral_sources.py', 'list_sources', 'PERMISSION', ('master_data.view', ), None),
    ('POST', '/api/referral-sources', 'routes/referral_sources.py', 'add_source', 'PERMISSION', ('master_data.manage', ), None),
    ('DELETE', '/api/referral-sources/{sid}', 'routes/referral_sources.py', 'delete_source', 'PERMISSION', ('master_data.manage', ), None),
    ('PUT', '/api/referral-sources/{sid}', 'routes/referral_sources.py', 'update_source', 'PERMISSION', ('master_data.manage', ), None),
    ('POST', '/api/referral-sources/{sid}/move', 'routes/referral_sources.py', 'move_source', 'PERMISSION', ('master_data.manage', ), None),
    ('GET', '/api/reports/arrears', 'routes/reports.py', 'arrears_list', 'PERMISSION', ('report.arrears.view', ), None),
    ('GET', '/api/reports/cashier', 'routes/reports.py', 'cashier_query', 'PERMISSION', ('report.cashier.view', ), None),
    ('GET', '/api/reports/cashier-query', 'routes/reports.py', 'cashier_query_detail', 'PERMISSION', ('report.cashier.view', ), None),
    ('GET', '/api/reports/cashier-query.csv', 'routes/reports.py', 'cashier_query_csv', 'PERMISSION', ('report.cashier.export', ), None),
    ('GET', '/api/reports/handle-category', 'routes/reports.py', 'handle_category', 'PERMISSION', ('report.operations.view', ), None),
    ('GET', '/api/reports/handle-category.csv', 'routes/reports.py', 'handle_category_csv', 'PERMISSION', ('report.operations.export', ), None),
    ('GET', '/api/reports/income', 'routes/reports.py', 'income_by_day', 'PERMISSION', ('report.finance.view', ), None),
    ('GET', '/api/reports/income-monthly', 'routes/reports.py', 'income_monthly', 'PERMISSION', ('report.finance.view', ), None),
    ('GET', '/api/reports/income.csv', 'routes/reports.py', 'income_csv', 'PERMISSION', ('report.finance.export', ), None),
    ('GET', '/api/reports/reconcile', 'routes/reports.py', 'reconcile_report', 'PERMISSION', ('report.operations.view', ), None),
    ('GET', '/api/reports/staff-workload', 'routes/reports.py', 'staff_workload', 'PERMISSION', ('report.performance.view', ), None),
    ('GET', '/api/reports/today-collection', 'routes/reports.py', 'today_collection', 'PERMISSION', ('report.cashier.view', ), None),
    ('GET', '/api/return-visits', 'routes/return_visits.py', 'return_visit_list', 'PERMISSION', ('return_visit.view', ), None),
    ('GET', '/api/return-visits/calendar', 'routes/return_visit_ops.py', 'return_visit_calendar', 'PERMISSION', ('return_visit.view', ), None),
    ('GET', '/api/return-visits/export', 'routes/return_visit_ops.py', 'return_visit_export', 'ALL_OF', ('patient.profile.export', 'return_visit.view', ), '回访导出同时需要患者导出与回访查看权限'),
    ('POST', '/api/return-visits/batch-delete', 'routes/return_visit_ops.py', 'batch_delete_return_visit', 'PERMISSION', ('return_visit.delete', ), None),
    ('DELETE', '/api/return-visits/{return_visit_id}', 'routes/return_visit_ops.py', 'soft_delete_return_visit', 'PERMISSION', ('return_visit.delete', ), None),
    ('GET', '/api/return-visits/{return_visit_id}', 'routes/return_visit_ops.py', 'return_visit_detail', 'PERMISSION', ('return_visit.view', ), None),
    ('PUT', '/api/return-visits/{return_visit_id}', 'routes/return_visits.py', 'update_return_visit', 'PERMISSION', ('return_visit.manage', ), None),
    ('POST', '/api/return-visits/{return_visit_id}/images', 'routes/return_visit_ops.py', 'upload_return_visit_image', 'PERMISSION', ('return_visit.manage', ), None),
    ('DELETE', '/api/return-visits/{return_visit_id}/images/{image_id}', 'routes/return_visit_ops.py', 'delete_return_visit_image', 'PERMISSION', ('return_visit.manage', ), None),
    ('GET', '/api/return-visits/{return_visit_id}/images/{image_id}/file', 'routes/return_visit_ops.py', 'return_visit_image_file', 'PERMISSION', ('return_visit.view', ), None),
    ('GET', '/api/role-permissions', 'routes/role_permissions.py', 'get_matrix', 'SYSTEM_ADMIN', (), None),
    ('PUT', '/api/role-permissions', 'routes/role_permissions.py', 'save_matrix', 'SYSTEM_ADMIN', (), None),
    ('GET', '/api/settings/appointment', 'routes/app_settings.py', 'get_appointment_settings', 'AUTHENTICATED_COMMON', (), None),
    ('PUT', '/api/settings/appointment', 'routes/app_settings.py', 'put_appointment_settings', 'PERMISSION', ('clinic_settings.manage', ), None),
    ('GET', '/api/settings/clinic', 'routes/app_settings.py', 'get_clinic_settings', 'AUTHENTICATED_COMMON', (), None),
    ('PUT', '/api/settings/clinic', 'routes/app_settings.py', 'put_clinic_settings', 'PERMISSION', ('clinic_settings.manage', ), None),
    ('GET', '/api/settings/customer-hub-dicts', 'routes/app_settings.py', 'get_customer_hub_dicts', 'CONDITIONAL', ('return_visit.view', 'communication.view', ), None),
    ('PUT', '/api/settings/customer-hub-dicts', 'routes/app_settings.py', 'put_customer_hub_dicts', 'CONDITIONAL', ('return_visit.manage', 'communication.manage', ), None),
    ('GET', '/api/settings/features', 'routes/app_settings.py', 'get_feature_settings', 'AUTHENTICATED_COMMON', (), None),
    ('PUT', '/api/settings/features', 'routes/app_settings.py', 'put_feature_settings', 'PERMISSION', ('clinic_settings.manage', ), None),
    ('GET', '/api/settings/pay-methods', 'routes/app_settings.py', 'get_pay_methods_settings', 'AUTHENTICATED_COMMON', (), None),
    ('PUT', '/api/settings/pay-methods', 'routes/app_settings.py', 'put_pay_methods_settings', 'PERMISSION', ('payment_method.manage', ), None),
    ('GET', '/api/settings/rooms', 'routes/app_settings.py', 'get_rooms_settings', 'AUTHENTICATED_COMMON', (), None),
    ('PUT', '/api/settings/rooms', 'routes/app_settings.py', 'put_rooms_settings', 'PERMISSION', ('clinic_settings.manage', ), None),
    ('GET', '/api/staff-admin/list', 'routes/staff.py', 'staff_admin_list', 'PERMISSION', ('staff.view', ), None),
    ('GET', '/api/staff-members', 'routes/staff.py', 'list_staff', 'AUTHENTICATED_DIRECTORY', (), None),
    ('POST', '/api/staff-members', 'routes/staff.py', 'create_staff', 'PERMISSION', ('staff.edit', ), None),
    ('DELETE', '/api/staff-members/{staff_id}', 'routes/staff.py', 'delete_staff', 'PERMISSION', ('staff.employment', ), None),
    ('PUT', '/api/staff-members/{staff_id}', 'routes/staff.py', 'update_staff', 'PERMISSION', ('staff.edit', ), None),
    ('POST', '/api/staff-members/{staff_id}/account', 'routes/staff.py', 'open_staff_account', 'PERMISSION', ('account.open', ), None),
    ('POST', '/api/staff-members/{staff_id}/reinstate', 'routes/staff.py', 'reinstate_staff', 'PERMISSION', ('staff.employment', ), None),
    ('GET', '/api/stats', 'routes/stats.py', 'stats', 'SECTIONED', ('patient.profile.view', 'billing.view', 'report.finance.view', 'audit.view', ), '至少登录且有一个工作台区块权限；各统计卡独立授权，不满足的卡不查询、不返回'),
    ('GET', '/api/stock-balance', 'routes/warehouse_stock.py', 'stock_balance', 'PERMISSION', ('warehouse.inventory.view', ), None),
    ('GET', '/api/stock-balance/alerts', 'routes/warehouse_stock.py', 'stock_balance_alerts', 'PERMISSION', ('warehouse.inventory.view', ), None),
    ('GET', '/api/stock-categories', 'routes/warehouse_items.py', 'list_categories', 'PERMISSION', ('warehouse.item.view', ), None),
    ('POST', '/api/stock-categories', 'routes/warehouse_items.py', 'create_category', 'PERMISSION', ('warehouse.item.manage', ), None),
    ('DELETE', '/api/stock-categories/{category_id}', 'routes/warehouse_items.py', 'delete_category', 'PERMISSION', ('warehouse.item.manage', ), None),
    ('PUT', '/api/stock-categories/{category_id}', 'routes/warehouse_items.py', 'update_category', 'PERMISSION', ('warehouse.item.manage', ), None),
    ('GET', '/api/stock-in', 'routes/warehouse_stock_in.py', 'list_stock_in', 'PERMISSION', ('warehouse.stock_in.view', ), None),
    ('POST', '/api/stock-in', 'routes/warehouse_stock_in.py', 'create_stock_in', 'PERMISSION', ('warehouse.stock_in.manage', ), None),
    ('POST', '/api/stock-in/{stock_in_id}/confirm', 'routes/warehouse_stock_in.py', 'confirm_stock_in', 'PERMISSION', ('warehouse.stock_in.confirm', ), None),
    ('GET', '/api/stock-items', 'routes/warehouse_items.py', 'list_items', 'PERMISSION', ('warehouse.item.view', ), None),
    ('POST', '/api/stock-items', 'routes/warehouse_items.py', 'create_item', 'PERMISSION', ('warehouse.item.manage', ), None),
    ('DELETE', '/api/stock-items/{item_id}', 'routes/warehouse_items.py', 'delete_item', 'PERMISSION', ('warehouse.item.manage', ), None),
    ('PUT', '/api/stock-items/{item_id}', 'routes/warehouse_items.py', 'update_item', 'PERMISSION', ('warehouse.item.manage', ), None),
    ('GET', '/api/stock-out', 'routes/warehouse_stock_out.py', 'list_stock_out', 'PERMISSION', ('warehouse.stock_out.view', ), None),
    ('POST', '/api/stock-out', 'routes/warehouse_stock_out.py', 'create_stock_out', 'PERMISSION', ('warehouse.stock_out.manage', ), None),
    ('POST', '/api/stock-out/{stock_out_id}/confirm', 'routes/warehouse_stock_out.py', 'confirm_stock_out', 'PERMISSION', ('warehouse.stock_out.confirm', ), None),
    ('GET', '/api/stock-take', 'routes/warehouse_stock_take.py', 'list_stock_take', 'PERMISSION', ('warehouse.stocktake.view', ), None),
    ('POST', '/api/stock-take', 'routes/warehouse_stock_take.py', 'create_stock_take', 'PERMISSION', ('warehouse.stocktake.manage', ), None),
    ('POST', '/api/stock-take/{stock_take_id}/confirm', 'routes/warehouse_stock_take.py', 'confirm_stock_take', 'PERMISSION', ('warehouse.stocktake.confirm', ), None),
    ('GET', '/api/store-stats/clinic-log', 'routes/store_stats.py', 'clinic_log', 'PERMISSION', ('report.operations.view', ), None),
    ('GET', '/api/store-stats/clinic-log.csv', 'routes/store_stats.py', 'clinic_log_csv', 'PERMISSION', ('report.operations.export', ), None),
    ('GET', '/api/store-stats/daily-settlement', 'routes/store_stats.py', 'daily_settlement', 'PERMISSION', ('report.finance.view', ), None),
    ('GET', '/api/store-stats/daily-settlement.csv', 'routes/store_stats.py', 'daily_settlement_csv', 'PERMISSION', ('report.finance.export', ), None),
    ('GET', '/api/store-stats/reconcile-calendar', 'routes/store_stats.py', 'reconcile_calendar', 'PERMISSION', ('report.operations.view', ), None),
    ('GET', '/api/store-stats/role-perf', 'routes/store_stats.py', 'role_perf', 'PERMISSION', ('report.performance.view', ), None),
    ('GET', '/api/suppliers', 'routes/warehouse_suppliers.py', 'list_suppliers', 'PERMISSION', ('warehouse.supplier.view', ), None),
    ('POST', '/api/suppliers', 'routes/warehouse_suppliers.py', 'create_supplier', 'PERMISSION', ('warehouse.supplier.manage', ), None),
    ('DELETE', '/api/suppliers/{supplier_id}', 'routes/warehouse_suppliers.py', 'delete_supplier', 'PERMISSION', ('warehouse.supplier.manage', ), None),
    ('PUT', '/api/suppliers/{supplier_id}', 'routes/warehouse_suppliers.py', 'update_supplier', 'PERMISSION', ('warehouse.supplier.manage', ), None),
    ('GET', '/api/today-follow-ups', 'routes/follow_ups.py', 'today_follow_ups', 'PERMISSION', ('return_visit.view', ), None),
    ('GET', '/api/today-inspection', 'routes/today_inspection.py', 'today_inspection', 'SECTIONED', ('patient.profile.view', 'billing.view', 'audit.view', ), '患者查看是入口门禁；金额和审计区块分别按权限与数据范围掩码'),
    ('GET', '/api/today-work', 'routes/today_work.py', 'today_work', 'SECTIONED', ('patient.profile.view', 'billing.view', 'audit.view', ), '患者查看是入口门禁；金额和审计区块分别按权限与数据范围掩码'),
    ('PUT', '/api/treatment-orders/{order_id}', 'routes/treatment_orders.py', 'edit_order', 'PERMISSION', ('treatment_order.manage', ), None),
    ('POST', '/api/treatment-orders/{order_id}/price', 'routes/treatment_orders.py', 'price_order', 'PERMISSION', ('treatment_order.price', ), None),
    ('POST', '/api/treatment-orders/{order_id}/void', 'routes/treatment_orders.py', 'void_order', 'PERMISSION', ('treatment_order.void', ), None),
    ('POST', '/api/treatment-plan-groups/{group_id}/select', 'routes/treatment_plans.py', 'select_group_option', 'PERMISSION', ('treatment_plan.manage', ), None),
    ('DELETE', '/api/treatment-plans/{plan_id}', 'routes/treatment_plans.py', 'delete_treatment_plan', 'PERMISSION', ('treatment_plan.delete', ), None),
    ('POST', '/api/treatment-plans/{plan_id}/bill', 'routes/treatment_plans.py', 'generate_plan_bill', 'PERMISSION', ('treatment_plan.bill', ), None),
    ('POST', '/api/treatment-plans/{plan_id}/status', 'routes/treatment_plans.py', 'change_plan_status', 'PERMISSION', ('treatment_plan.status', ), None),
    ('GET', '/api/users', 'routes/users.py', 'list_users', 'PERMISSION', ('account.view', ), None),
    ('POST', '/api/users', 'routes/users.py', 'create_user', 'PERMISSION', ('account.open', ), None),
    ('PUT', '/api/users/{user_id}', 'routes/users.py', 'update_user', 'PERMISSION', ('account.open', ), None),
    ('POST', '/api/users/{user_id}/reset-password', 'routes/users.py', 'reset_password', 'PERMISSION', ('account.security', ), None),
    ('POST', '/api/users/{user_id}/system-admin/grant', 'routes/users.py', 'grant_system_admin', 'SYSTEM_ADMIN', (), None),
    ('POST', '/api/users/{user_id}/system-admin/revoke', 'routes/users.py', 'revoke_system_admin', 'SYSTEM_ADMIN', (), None),
    ('GET', '/api/versions', 'routes/versions.py', 'versions', 'CONDITIONAL', ('patient.profile.view', 'medical_record.view', 'appointment.view', 'return_visit.view', ), None),
)

ROUTE_POLICIES = tuple(
    RoutePolicy(method, path, source, function, policy_type, permissions, note)
    for (method, path, source, function, policy_type, permissions, note) in _ROUTE_POLICY_ROWS
)

# 以 (method, path) 为键的只读索引；数据保证该键唯一。
ROUTE_POLICY_BY_KEY = MappingProxyType(
    {(policy.method, policy.path): policy for policy in ROUTE_POLICIES}
)

# 5 分钟内输过当前密码才可执行：所有真实删除与已批准的高风险变更。
# 登录本身会记录一次近期确认；超过 5 分钟后由全局授权器在进入处理函数前拦截。
RECENT_REAUTH_ROUTE_KEYS = frozenset(
    (policy.method, policy.path)
    for policy in ROUTE_POLICIES
    if policy.method == "DELETE"
) | frozenset(
    {
        ("POST", "/api/bills/{bill_id}/refund"),
        (
            "POST",
            "/api/patients/{patient_identity}/member-account/refund",
        ),
        ("POST", "/api/recycle-bin/restore"),
        ("POST", "/api/return-visits/batch-delete"),
        ("POST", "/api/staff-members/{staff_id}/reinstate"),
        ("POST", "/api/users/{user_id}/system-admin/grant"),
        ("POST", "/api/users/{user_id}/system-admin/revoke"),
    }
)
